spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: sales-point-ms-security
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=global_security;trustServerCertificate=true
    username: sa
    password: contra4Dmin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


server:
  port: 8080

log:
  path: C:\Users\Yessi\Documents\logs\${spring.application.name}



